### ISSUE TITLE
 documentation 

### ISSUE THREAD

**Issue by fhfavaretto** [houstonsantos/DevDockerProtheus#1]
acredito que esteja faltando alguns passos na documentação de como iniciar os containers, consegue detalhar melhor ?

**Comment by houstonsantos** [comment]
OI fhfavaretto, o que pude ver e que tem algum bug na criação do banco em SQL Server, não tive tempo de verificar o que esta ocorrendo, pois segui a documentação do SQL Server para containers, então se for usar SQL Server você pode alterar o script de entrypoint.sh retirando a execução do script db_mssql.sh que cria o banco, e criar o banco na mão, isso deve resolver.

Agora se você tiver usando o Postgresql no windows não tem problema algum, pois algumas pessoas já usaram e validaram. Porem no Mac OS é preciso aumentar a memória do Docker para 4GB, isso eu realmente esqueci de mencionar na documentação, lembrando a memória do Docker e não do container, isso poderia ser feito de outra forma usando ulimit, para os diretórios, porem como não é um ambiente de produção não fiz, numa próxima atualização farei.

**Comment by fhfavaretto** [comment]
@houstonsantos  Obrigado pelo feedback, entendi obrigado pelas explicações como eu estou utilizando uma arquitetura m1 Apple Silicon, o SQL Server ainda não esta otimizado, tentarei fazer algumas melhorias e mando um PR para você revisar.

desde já gostaria de dizer que seu projeto ficou muito legal parabéns pela iniciativa.
