### ISSUE TITLE
binarios

### ISSUE THREAD

**Issue by leefjb** [houstonsantos/DevDockerProtheus#2]
Apenas para informação, é necessário baixar os binarios e copiar cada um deles em uma pasta protheus dentro da pasta do projeto de acordo com cada chamada nos scripts correto?

Sei que é coisa leiga, mas é bom deixar documentado...

**Comment by houstonsantos** [comment]
Isso mesmo, você deve deixar conforme estrutura dos dockerfiles. O README foi atualizado, e também atualizei a conexão com o driver odbc/dbaccess pois vê que não estava finalizando a conexão, agora está ok.
